# Examples
Examples from the paper.

In [1]:
import numpy as np
import cokriging as ck

## Example 1
Carr, Myers, and Glass (1985) data

In [2]:
model = np.array(
    [[1, 1],
     [4, 30]],
)
c = np.array([
    [[1.5, -0.975],
     [-0.975, 0.5]],
    [[12.0, -5.9],
     [-5.9,  1.8]],
])

## Example 2
Block cokriging in 3D, with three variables and a missing value

In [3]:
x = np.array([[-3,  6,  1,  5,  0, 41],
              [-8, -5,  0, 52, 38, np.nan],
              [ 3, -3,  3, 67,  6, 58]])

x0 = np.array([[  0,  0,  0],
               [ 10, 20, 33]])

block = np.array([5, 10, 5])
nd = np.array([3, 3, 2])
model = np.array([[ 1,  1,  1,  1,  0,  0,  0],
                  [ 4, 50, 30, 10,  0,  0, 30]])
c = np.array([[[ 20,  10,  5],
               [ 10,  25,  3],
               [  5,   3, 12]],
                
              [[ 50, -20, 15],
               [-20,  25, -7],
               [ 15,  -7, 15]],])
itype = 3
avg = np.array([0, 0, 0])
ival = 0
nk = 3
rad = 100
ntok = 2

x0s, s, sv, id, b = ck.cokri(x, x0, model, c, itype, avg, block, nd, ival, nk, rad, ntok)

(27, 3) (1, 3)
[[-3.33333333e-01 -5.55111512e-17  3.33333333e-01]
 [-3.33333333e-01 -5.55111512e-17  3.33333333e-01]
 [-3.33333333e-01 -5.55111512e-17  3.33333333e-01]
 [-3.33333333e-01 -5.55111512e-17  3.33333333e-01]
 [-3.33333333e-01 -5.55111512e-17  3.33333333e-01]
 [-3.33333333e-01 -5.55111512e-17  3.33333333e-01]
 [-3.33333333e-01 -5.55111512e-17  3.33333333e-01]
 [-3.33333333e-01 -5.55111512e-17  3.33333333e-01]
 [-3.33333333e-01 -5.55111512e-17  3.33333333e-01]
 [-3.33333333e-01 -5.55111512e-17  3.33333333e-01]
 [-3.33333333e-01 -5.55111512e-17  3.33333333e-01]
 [-3.33333333e-01 -5.55111512e-17  3.33333333e-01]
 [-3.33333333e-01 -5.55111512e-17  3.33333333e-01]
 [-3.33333333e-01 -5.55111512e-17  3.33333333e-01]
 [-3.33333333e-01 -5.55111512e-17  3.33333333e-01]
 [-3.33333333e-01 -5.55111512e-17  3.33333333e-01]
 [-3.33333333e-01 -5.55111512e-17  3.33333333e-01]
 [-3.33333333e-01 -5.55111512e-17  3.33333333e-01]
 [-3.33333333e-01 -5.55111512e-17  3.33333333e-01]
 [-3.33333333e-0

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 27 and the array at index 1 has size 1